### PR TITLE
fix: (keymap) resolve #90

### LINKED ISSUE #90: Use D instead of d$ and Y instead of y$

### PR DESCRIPTION
**Pull request by olivertzeng**

### CODE REVIEW

**Comment by m4xshen** [comment]
@olivertzeng You need to escape `$` since it is a special character in [Lua string patterns](https://www.lua.org/pil/20.2.html):

```lua
["d%$"] = {
   message = function()
      return "Use D instead of d$"
   end,
   length = 2,
},
```

Same for the `y$`. After you change that it can be merged!

**Comment by olivertzeng** [comment]
Alr thanks for the tip!
 Sent from Proton Mail for iOS 
於 週二, 6月 4, 2024 時間 16:01, Max Shen ***@***.***&gt; 寫道：  @olivertzeng You need to escape $ since it is a special character in Lua string patterns:
["d%$"] = {
   message = function()
      return "Use D instead of d$"
   end,
   length = 2,
},
Same for the y$. After you change that it can be merged!

**Comment by m4xshen** [comment]
Thanks for the PR! You can now update hardtime.nvim to the latest version to use it. Btw hardtime.nvim now requires Neovim >= 0.10 due to this bug fix #77

**Comment by olivertzeng** [comment]
Nice
 Sent from Proton Mail for iOS 
於 週二, 6月 4, 2024 時間 16:21, Max Shen ***@***.***&gt; 寫道：  Thanks for the PR! You can now update hardtime.nvim to the latest version to use it. Btw hardtime.nvim now requires Neovim &gt;= 0.10 due to this bug fix #77

**Pull request merged**
