### PR TITLE
Feature: Expose state of 'enabled'

### PR DESCRIPTION
**Pull request by schilkp**
Hi!

Adds a `M.is_enabled()` function to expose the current state of hardtime.  Useful for statuslines and many different things :)

Apologies if this is already possible - I had a very quick look and did not see it.

Thanks!

### CODE REVIEW

**Comment by m4xshen** [comment]
How about just make the `enabled` variable exposed?

change this:
```lua
local enabled = false
```

to this:
```lua
M.enabled = false
```

**Comment by schilkp** [comment]
If that works - sure. I don't know lua very well. Is the`M` table effectively a singleton or would multiple `require('hardtime')`s have individual `M` tables? I presumed it was a local for that reason :)

**Comment by m4xshen** [comment]
Thank for the PR!
Btw, I just rename it from `M.enabled` to `M.is_enabled`. I found that this is more clear.

**Comment by schilkp** [comment]
Thanks!

**Pull request merged**
