### PR TITLE
feat: support glob pattern for disabled_filetypes

### PR DESCRIPTION
**Pull request by heywhy**
Specifying buffer types (to disable hardtime for) individually can be tedious, especially for buffers that share a common prefix like `Neogit`, so I've included a small glob-like support that allows users to specify `Neogit*` and it matches all Neogit buffers.

### CODE REVIEW

**Comment by m4xshen** [comment]
@heywhy Sorry I've been busy recently. I'll review this today asap!

**Comment by m4xshen** [comment]
@heywhy I just rewrote the matching logic and removed the redundant part. It should work same as before. If this looks good to you I'll merge it!

**Comment by heywhy** [comment]
LGTM! I apologize for my cranky implementation, I have little to no knowledge of Lua. 😄

**Comment by m4xshen** [comment]
Great, thanks for your contribution :heart:

**Pull request merged**
